import type { MessageResType } from "../types/message.types";
import type { Task } from "../types/task.types";

export const mockTasks: Task[] = [
  {
    id: 1,
    contactId: 1,
    userId: 1,
    title: "Follow up sobre propuesta enviada",
    description: "Contactar al cliente para conocer feedback de la propuesta",
    type: "follow-up",
    status: "pending",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
  },
  {
    id: 2,
    contactId: 1,
    userId: 1,
    title: "Enviar documentación adicional",
    description: "Adjuntar brochure y detalles técnicos del producto",
    type: "reminder",
    status: "done",
    dueDate: new Date(new Date().setDate(new Date().getDate() - 2)),
    createdAt: new Date(),
  },
  {
    id: 3,
    contactId: 2,
    userId: 1,
    title: "Agendar llamada de demo",
    description: "Coordinar reunión por Google Meet para demo del sistema",
    type: "follow-up",
    status: "pending",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    createdAt: new Date(),
  },
  {
    id: 4,
    contactId: 3,
    userId: 2,
    title: "Revisar contrato",
    description: "Validar términos antes de enviar al cliente",
    type: "reminder",
    status: "pending",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 7)),
    createdAt: new Date(),
  },
  {
    id: 5,
    contactId: 2,
    userId: 1,
    title: "Confirmar recepción de email",
    description: "Verificar que el cliente haya recibido el correo enviado",
    type: "follow-up",
    status: "done",
    dueDate: new Date(new Date().setDate(new Date().getDate() - 1)),
    createdAt: new Date(),
  },
];


export const mockAvailableTags = [
    "Enterprise",
    "Startup",
    "Priority",
    "Q1 Priority",
    "Q2 Priority",
    "Inbound",
    "Outbound",
    "Referral",
    "Cold Outreach",
    "Upsell",
    "Finance",
    "Healthcare",
    "Retail",
    "Logistics",
    "Tech",
]