import type { MessageResType } from "../types/message.types";
import type { Task } from "../types/task.types";

export const mockTasks: Task[] = [
  {
    id: 1,
    contactId: 1,
    userId: 1,
    title: "Follow up sobre propuesta enviada",
    description: "Contactar al cliente para conocer feedback de la propuesta",
    type: "follow-up",
    status: "pending",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
  },
  {
    id: 2,
    contactId: 1,
    userId: 1,
    title: "Enviar documentación adicional",
    description: "Adjuntar brochure y detalles técnicos del producto",
    type: "reminder",
    status: "done",
    dueDate: new Date(new Date().setDate(new Date().getDate() - 2)),
    createdAt: new Date(),
  },
  {
    id: 3,
    contactId: 2,
    userId: 1,
    title: "Agendar llamada de demo",
    description: "Coordinar reunión por Google Meet para demo del sistema",
    type: "follow-up",
    status: "pending",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    createdAt: new Date(),
  },
  {
    id: 4,
    contactId: 3,
    userId: 2,
    title: "Revisar contrato",
    description: "Validar términos antes de enviar al cliente",
    type: "reminder",
    status: "pending",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 7)),
    createdAt: new Date(),
  },
  {
    id: 5,
    contactId: 2,
    userId: 1,
    title: "Confirmar recepción de email",
    description: "Verificar que el cliente haya recibido el correo enviado",
    type: "follow-up",
    status: "done",
    dueDate: new Date(new Date().setDate(new Date().getDate() - 1)),
    createdAt: new Date(),
  },
];


export const mockMessages: MessageResType[] = [
    {
        id: 1,
        userId: 1,
        channel: "whatsapp",
        direction: "inbound",
        content: "Hola! Estoy interesado en el producto.",
        createdAt: new Date(),
        externalId: "msg_001",
        messageType: "text",
        status: "delivered",
        conversationId: 101,
    },
    {
        id: 2,
        userId: 1,
        channel: "whatsapp",
        direction: "outbound",
        content: "¡Genial! ¿Querés que te pase más info?",
        createdAt: new Date(),
        externalId: "msg_002",
        messageType: "text",
        status: "read",
        conversationId: 101,
    },
    {
        id: 3,
        userId: 1,
        channel: "email",
        direction: "outbound",
        content: "Te enviamos la propuesta por este medio.",
        createdAt: new Date(),
        externalId: "msg_003",
        messageType: "text",
        status: "sent",
        conversationId: 102,
    },
    {
        id: 4,
        userId: 2,
        channel: "email",
        direction: "inbound",
        content: "Recibido, lo reviso y te aviso.",
        createdAt: new Date(),
        externalId: "msg_004",
        messageType: "text",
        status: "delivered",
        conversationId: 102,
    },
    {
        id: 5,
        userId: 1,
        channel: "whatsapp",
        direction: "outbound",
        content: "Te dejo un PDF con detalles.",
        createdAt: new Date(),
        externalId: "msg_005",
        messageType: "media",
        fileUrl: "https://example.com/file.pdf",
        status: "sent",
        conversationId: 101,
    },
    {
        id: 6,
        userId: 2,
        channel: "whatsapp",
        direction: "inbound",
        content: "Gracias! Lo veo.",
        createdAt: new Date(),
        externalId: "msg_006",
        messageType: "text",
        status: "read",
        conversationId: 101,
    },
    {
        id: 7,
        userId: 1,
        channel: "email",
        direction: "outbound",
        content: "¿Pudiste revisar la propuesta?",
        createdAt: new Date(),
        externalId: "msg_007",
        messageType: "text",
        status: "sent",
        conversationId: 102,
    },
    {
        id: 8,
        userId: 2,
        channel: "email",
        direction: "inbound",
        content: "Sí, tengo algunas dudas.",
        createdAt: new Date(),
        externalId: "msg_008",
        messageType: "text",
        status: "delivered",
        conversationId: 102,
    },
    {
        id: 9,
        userId: 1,
        channel: "whatsapp",
        direction: "outbound",
        content: "¿Querés que coordinemos una llamada?",
        createdAt: new Date(),
        externalId: "msg_009",
        messageType: "text",
        status: "read",
        conversationId: 101,
    },
    {
        id: 10,
        userId: 2,
        channel: "whatsapp",
        direction: "inbound",
        content: "Sí, mañana por la tarde me viene bien.",
        createdAt: new Date(),
        externalId: "msg_010",
        messageType: "text",
        status: "delivered",
        conversationId: 101,
    },
];


export const mockAvailableTags = [
    "Enterprise",
    "Startup",
    "Priority",
    "Q1 Priority",
    "Q2 Priority",
    "Inbound",
    "Outbound",
    "Referral",
    "Cold Outreach",
    "Upsell",
    "Finance",
    "Healthcare",
    "Retail",
    "Logistics",
    "Tech",
]